{% set name = "indexedconv" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/IndexedConv-{{ version }}.tar.gz
  sha256: 3fa821088b9c7d2726bf4456e8d68779b9c0b4ed5cb3fda0ba5c023beb5d4f73

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytorch >=1.7
    - torchvision
    - numpy
    - matplotlib-base
    - h5py

test:
  imports:
    - indexedconv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IndexedConv/IndexedConv
  summary: An implementation of indexed convolution and pooling
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vuillaut
